---
latitude: 40.75967
longitude: -73.97729
map_zoom: 12
name: 3 West Club
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 3 W 51st Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10019'
_hotel_id: 3WE930
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
